export const MOB_TYPES = {
  sheep: {
    name: "Sheep",
    passive: true,
    maxHealth: 8,
    speed: 0.72,
    fleeSpeed: 1.55,
    bodyColor: "#eeeeee",
    headColor: "#c7b8a6",
    scale: [0.95, 0.85, 1.15],
    loot: [
      { item: "wool", min: 1, max: 2, chance: 1 },
      { item: "raw_mutton", min: 1, max: 2, chance: 1 },
    ],
  },
  cow: {
    name: "Cow",
    passive: true,
    maxHealth: 10,
    speed: 0.62,
    fleeSpeed: 1.35,
    bodyColor: "#6d432b",
    headColor: "#4d3021",
    scale: [1.1, 1, 1.35],
    loot: [
      { item: "raw_beef", min: 1, max: 3, chance: 1 },
      { item: "leather", min: 0, max: 2, chance: 0.75 },
    ],
  },
  pig: {
    name: "Pig",
    passive: true,
    maxHealth: 10,
    speed: 0.68,
    fleeSpeed: 1.5,
    bodyColor: "#d98989",
    headColor: "#e5a0a0",
    scale: [1, 0.82, 1.2],
    loot: [{ item: "raw_porkchop", min: 1, max: 3, chance: 1 }],
  },
  chicken: {
    name: "Chicken",
    passive: true,
    maxHealth: 5,
    speed: 0.8,
    fleeSpeed: 1.7,
    bodyColor: "#f4f1dc",
    headColor: "#f8f4df",
    scale: [0.62, 0.62, 0.68],
    loot: [{ item: "raw_chicken", min: 1, max: 2, chance: 1 }],
  },
  horse: {
    name: "Horse",
    passive: true,
    tameable: true,
    rideable: true,
    tameFoods: ["apple", "wheat"],
    maxHealth: 24,
    speed: 1.15,
    fleeSpeed: 2.05,
    mountedSpeed: 9.5,
    bodyColor: "#805334",
    headColor: "#9d6b43",
    scale: [1.05, 1.18, 1.55],
    loot: [{ item: "leather", min: 0, max: 2, chance: 0.7 }],
  },
  turtle: {
    name: "Sea Turtle",
    passive: true,
    amphibious: true,
    maxHealth: 14,
    speed: 0.48,
    swimSpeed: 0.72,
    bodyColor: "#477f4b",
    headColor: "#72a45f",
    scale: [1.05, 0.45, 1.3],
    loot: [{ item: "seagrass", min: 0, max: 2, chance: 0.65 }],
  },
  wolf: {
    name: "Wolf",
    friendly: false,
    neutralPredator: true,
    tameable: true,
    tameFoods: ["bone", "raw_beef", "raw_mutton", "raw_porkchop", "raw_chicken"],
    maxHealth: 18,
    speed: 1.55,
    attackDamage: 3,
    attackRange: 1.25,
    attackCooldown: 0.72,
    aggroRange: 13,
    bodyColor: "#aeb6bd",
    headColor: "#d4d8dc",
    scale: [0.82, 0.8, 1.05],
    loot: [],
  },
  iron_golem: {
    name: "Frontier Golem",
    friendly: true,
    maxHealth: 45,
    speed: 0.72,
    attackDamage: 8,
    attackRange: 1.65,
    attackCooldown: 1.2,
    aggroRange: 16,
    bodyColor: "#b9b8aa",
    headColor: "#d2d0c1",
    scale: [1.15, 1.9, 0.72],
    loot: [],
  },
  zombie: {
    name: "Zombie",
    hostile: true,
    maxHealth: 14,
    speed: 1.05,
    attackDamage: 2,
    attackRange: 1.35,
    attackCooldown: 1.05,
    bodyColor: "#345d83",
    headColor: "#5f8f55",
    scale: [0.72, 1.65, 0.52],
    loot: [{ item: "rotten_flesh", min: 0, max: 2, chance: 0.85 }],
  },
  skeleton: {
    name: "Skeleton",
    hostile: true,
    maxHealth: 12,
    speed: 1.15,
    attackDamage: 3,
    attackRange: 1.45,
    attackCooldown: 1.1,
    bodyColor: "#d8d6c9",
    headColor: "#f0eee1",
    scale: [0.64, 1.58, 0.46],
    loot: [{ item: "bone", min: 0, max: 2, chance: 0.9 }],
  },
  slime: {
    name: "Slime",
    hostile: true,
    maxHealth: 8,
    speed: 0.82,
    attackDamage: 1,
    attackRange: 1.15,
    attackCooldown: 0.9,
    bodyColor: "#63c751",
    headColor: "#63c751",
    scale: [0.95, 0.95, 0.95],
    loot: [{ item: "slime_ball", min: 0, max: 2, chance: 0.75 }],
  },
  fish: {
    name: "Reef Fish",
    passive: true,
    aquatic: true,
    maxHealth: 4,
    speed: 1.2,
    bodyColor: "#e5a843",
    headColor: "#f0c56a",
    scale: [0.58, 0.34, 0.9],
    loot: [{ item: "raw_fish", min: 1, max: 1, chance: 1 }],
  },
  big_fish: {
    name: "Big Fish",
    passive: true,
    aquatic: true,
    maxHealth: 10,
    speed: 0.9,
    bodyColor: "#4b78a8",
    headColor: "#6d98c5",
    scale: [1.05, 0.62, 1.8],
    loot: [{ item: "raw_fish", min: 2, max: 4, chance: 1 }],
  },
  shark: {
    name: "Shark",
    hostile: true,
    aquatic: true,
    alwaysActive: true,
    maxHealth: 24,
    speed: 1.65,
    attackDamage: 5,
    attackRange: 1.8,
    attackCooldown: 1,
    aggroRange: 18,
    bodyColor: "#536b79",
    headColor: "#6e8795",
    scale: [1.15, 0.72, 2.35],
    loot: [{ item: "raw_fish", min: 2, max: 4, chance: 1 }],
  },
  dolphin: {
    name: "Dolphin",
    friendly: true,
    aquatic: true,
    alwaysActive: true,
    maxHealth: 16,
    speed: 1.9,
    attackDamage: 4,
    attackRange: 1.5,
    attackCooldown: 0.7,
    aggroRange: 16,
    bodyColor: "#5f91a9",
    headColor: "#79abc1",
    scale: [0.95, 0.58, 1.75],
    loot: [],
  },
  bird: {
    name: "Sky Bird",
    passive: true,
    flying: true,
    maxHealth: 4,
    speed: 2.1,
    bodyColor: "#d7d6cd",
    headColor: "#f0ad4e",
    scale: [0.52, 0.3, 0.66],
    loot: [],
  },
  boat: {
    name: "Oak Boat",
    vehicle: true,
    rideable: true,
    aquatic: true,
    alwaysActive: true,
    maxHealth: 12,
    speed: 0,
    mountedSpeed: 7.8,
    bodyColor: "#8d5d31",
    headColor: "#a6733f",
    scale: [1.45, 0.42, 2.05],
    loot: [{ item: "boat", min: 1, max: 1, chance: 1 }],
  },
};

export function createMob(id, type, x, y, z, random = Math.random) {
  const definition = MOB_TYPES[type];
  return {
    id,
    type,
    x,
    y,
    z,
    health: definition.maxHealth,
    maxHealth: definition.maxHealth,
    direction: random() * Math.PI * 2,
    wanderTimer: 1 + random() * 4,
    tamed: false,
    tameProgress: 0,
    customName: "",
  };
}

export function rollMobLoot(type, random = Math.random) {
  const definition = MOB_TYPES[type];
  if (!definition) return {};

  return (definition.loot || []).reduce((result, drop) => {
    if (random() > drop.chance) return result;
    const amount = drop.min + Math.floor(random() * (Math.max(drop.max - drop.min, 0) + 1));
    if (amount > 0) result[drop.item] = (result[drop.item] || 0) + amount;
    return result;
  }, {});
}

export function isNightOnly(definition) {
  return Boolean(definition?.hostile && !definition?.alwaysActive && !definition?.aquatic);
}
