import React, { useMemo } from "react";
import { Box, Button, Chip, LinearProgress, Paper, Stack, Typography } from "@mui/material";
import AgricultureIcon from "@mui/icons-material/Agriculture";
import ConstructionIcon from "@mui/icons-material/Construction";
import GppGoodIcon from "@mui/icons-material/GppGood";
import PhishingIcon from "@mui/icons-material/Phishing";
import PetsIcon from "@mui/icons-material/Pets";
import Inventory2Icon from "@mui/icons-material/Inventory2";
import { useDispatch, useSelector } from "react-redux";
import { collectColonyStorage, toggleColonyStation } from "../../../features/world/worldSlice";
import { COLONY_JOB_TYPES } from "../../../game/config/colony";
import { getItemDefinition } from "../../../game/config/blockTypes";
import ItemIcon from "../../items/icons/ItemIcon";
const JOB_ICONS={guard:GppGoodIcon,miner:ConstructionIcon,farmer:AgricultureIcon,rancher:PetsIcon,fisher:PhishingIcon};
function StorageGrid({storage}){const entries=Object.entries(storage||{}).filter(([,amount])=>amount>0);if(!entries.length)return <Typography color="text.secondary">Workers have not delivered anything yet.</Typography>;return <div className="colony-storage-grid">{entries.map(([item,amount])=><Paper key={item} className="colony-storage-item"><ItemIcon itemId={item} size={42} alt=""/><div><Typography fontWeight={1000}>{getItemDefinition(item).name}</Typography><Typography variant="caption">{amount} stored</Typography></div></Paper>)}</div>;}
export default function ColonyPanel({stationKey=null}){const dispatch=useDispatch();const colony=useSelector((s)=>s.world.colony);const selected=useMemo(()=>colony.stations.find((st)=>st.key===stationKey)||null,[colony.stations,stationKey]);const stations=selected?[selected,...colony.stations.filter((st)=>st.id!==selected.id)]:colony.stations;const total=Object.values(colony.storage||{}).reduce((sum,v)=>sum+(Number(v)||0),0);return <Box className="colony-command-panel"><div className="rpg-section-heading"><div><Typography variant="h4" fontWeight={1000}>Frontier colony command</Typography><Typography color="text.secondary">Craft and place job boxes to recruit guards, miners, farmers, animal keepers, and fishers. Planning runs at a fixed low-frequency tick.</Typography></div><Button variant="contained" startIcon={<Inventory2Icon/>} disabled={!total} onClick={()=>dispatch(collectColonyStorage())}>Collect {total||"storage"}</Button></div><div className="colony-summary-grid">{Object.entries(colony.totals||{}).map(([key,value])=><Paper key={key} className="colony-summary-card"><Typography variant="overline">{key.replace(/([A-Z])/g," $1")}</Typography><Typography variant="h4" fontWeight={1000}>{value||0}</Typography></Paper>)}</div><Typography variant="h5" fontWeight={1000} sx={{mt:3,mb:1}}>Worker stations</Typography><Stack spacing={1.2}>{stations.length===0&&<Paper sx={{p:2.5}}><Typography color="text.secondary">Place a colony job box to recruit your first worker.</Typography></Paper>}{stations.map((station)=>{const job=COLONY_JOB_TYPES[station.job];const Icon=JOB_ICONS[station.job]||ConstructionIcon;return <Paper key={station.id} className={`colony-station-card ${station.id===selected?.id?"is-selected":""}`}><div className="colony-station-icon" style={{"--job-color":job?.color||"#777"}}><Icon/></div><div className="colony-station-copy"><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={1000}>{job?.label||station.job}</Typography><Chip size="small" label={station.workerName||"Colonist"}/><Chip size="small" color={station.enabled?"success":"default"} label={station.enabled?"Working":"Paused"}/></Stack><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>{station.status||job?.description}</Typography><LinearProgress variant="determinate" value={(station.progress||0)*100} sx={{mt:1,height:7}}/><Typography variant="caption">Production: {station.production||0} · Station level {station.level||1}</Typography></div><Button color={station.enabled?"warning":"success"} onClick={()=>dispatch(toggleColonyStation(station.id))}>{station.enabled?"Pause":"Resume"}</Button></Paper>;})}</Stack><Typography variant="h5" fontWeight={1000} sx={{mt:3,mb:1}}>Shared colony storage</Typography><StorageGrid storage={colony.storage}/></Box>;}
